[versions]
apache-pdfbox = "3.0.1"
kotlin-jvm = "1.9.20"

[libraries]
apache-pdfbox = { module = "org.apache.pdfbox:pdfbox", version.ref = "apache-pdfbox" }

[plugins]
jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin-jvm" }
