[versions]

junit5 = "5.10.0"
assertj-core = "3.23.1"
junit-platform = "1.10.1"
kotlin-junit5 = "1.9.20"
mockk = "1.9.3"

[libraries]
kotlin-test-junit5 = { module = "org.jetbrains.kotlin:kotlin-test-junit5", version.ref = "kotlin-junit5" }
junit-jupiter-engine = { module = "org.junit.jupiter:junit-jupiter-engine", version.ref = "junit5" }
junit-jupiter-api = { module = "org.junit.jupiter:junit-jupiter-api", version.ref = "junit5" }
junit-platform-launcher = { module = "org.junit.platform:junit-platform-launcher", version.ref = "junit-platform" }
assertj-core = { module = "org.assertj:assertj-core", version.ref = "assertj-core" }
mockk = { module = "io.mockk:mockk", version.ref = "mockk" }

